services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: sportevents
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d sportevents" ]
        interval: 5s
        timeout: 5s
        retries: 5

  app:
    build: .
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sportevents
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: ${SERVER_PORT:-8080}
      GROQ_API_KEY: ${GROQ_API_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
    depends_on:
      - db

volumes:
  postgres_data:
