spring.application.name=sporteventsMVP

# Dotenv
springdotenv.enabled=true
springdotenv.filename=.env
springdotenv.ignoreIfMissing=true

# Base de datos
sspring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${SERVER_PORT:8080}


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Desactivar security por ahora (hasta que configuremos JWT)
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000